name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.3.2
homepage: https://github.com/builttoroam/device_calendar/tree/master

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  sprintf: ^7.0.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=3.2.3 <4.5.0"
  flutter: ">=1.12.13"
